# Generated by Django 3.1 on 2020-09-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actu_titre', models.CharField(max_length=300)),
                ('auteur', models.CharField(max_length=300)),
                ('actu_content', models.TextField()),
                ('actu_province', models.CharField(choices=[('Équateur', 'Équateur'), ('Haut-Katanga', 'Haut-Katanga'), ('Haut-Lomami', 'Haut-Lomami'), ('Haut-Uele', 'Haut-Uele'), ('Ituri', 'Ituri'), ('Kasaï', 'Kasaï'), ('Kasaï-Central', 'Kasaï-Central'), ('Kasaï-Oriental', 'Kasaï-Oriental'), ('Kinshasa', 'Kinshasa'), ('Kongo-Central', 'Kongo-Central'), ('Kwango', 'Kwango'), ('Kwilu', 'Kwilu'), ('Lomami', 'Lomami'), ('Lualaba', 'Lualaba'), ('Mai-Ndombe', 'Mai-Ndombe'), ('Maniema', 'Maniema'), ('Mongala', 'Mongala'), ('Nord-Kivu', 'Nord-Kivu'), ('Nord-Ubangi', 'Nord-Ubangi'), ('Sankuru', 'Sankuru'), ('Sud-Kivu', 'Sud-Kivu'), ('Sud-Ubangi', 'Sud-Ubangi'), ('Tanganyika', 'Tanganyika'), ('Tshopo', 'Tshopo'), ('Tshuapa', 'Tshuapa'), ('INTERNATIONALE', 'INTERNATIONALE')], max_length=300)),
                ('actu_categorie', models.CharField(choices=[('ACTUALITE', 'Actualités'), ('ECONOMIE', 'Economie'), ('SANTE', 'Santé'), ('SECURITE', 'Sécurité'), ('FORMATIONS', 'Formations'), ('AUTRES', 'AUTRES')], max_length=300)),
                ('actu_image', models.ImageField(upload_to='actu_img/')),
                ('actu_image_1', models.ImageField(blank=True, upload_to='actu_img/', verbose_name='Facultatif')),
                ('actu_image_2', models.ImageField(blank=True, upload_to='actu_img/', verbose_name='Facultatif')),
                ('actu_image_3', models.ImageField(blank=True, upload_to='actu_img/', verbose_name='Facultatif')),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
